version: '2'
services:
  lbsliveenterprise-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/LBSLiveEnterprise/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=LBSLiveEnterprise
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
